//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZKonfigurator.BusinessModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EquipmentResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquipmentResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFZKonfigurator.BusinessModels.Resources.EquipmentResx", typeof(EquipmentResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS.
        /// </summary>
        internal static string ABS {
            get {
                return ResourceManager.GetString("ABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klimaanlage.
        /// </summary>
        internal static string AirConditioner {
            get {
                return ResourceManager.GetString("AirConditioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-Rad-Antrieb.
        /// </summary>
        internal static string AllWheelDrive {
            get {
                return ResourceManager.GetString("AllWheelDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klimaautomatisierung.
        /// </summary>
        internal static string ClimateAutomation {
            get {
                return ResourceManager.GetString("ClimateAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempomat.
        /// </summary>
        internal static string CruiseControl {
            get {
                return ResourceManager.GetString("CruiseControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multifunktionslenkrad.
        /// </summary>
        internal static string MultiFunctionSteeringWheel {
            get {
                return ResourceManager.GetString("MultiFunctionSteeringWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigationsgerät.
        /// </summary>
        internal static string NavigationDevice {
            get {
                return ResourceManager.GetString("NavigationDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parksensoren.
        /// </summary>
        internal static string ParkingSensors {
            get {
                return ResourceManager.GetString("ParkingSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitzheizung.
        /// </summary>
        internal static string SeatHeater {
            get {
                return ResourceManager.GetString("SeatHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound System.
        /// </summary>
        internal static string SoundSystem {
            get {
                return ResourceManager.GetString("SoundSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhängerkupplung.
        /// </summary>
        internal static string TowCoupling {
            get {
                return ResourceManager.GetString("TowCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenon Licht.
        /// </summary>
        internal static string XenonLight {
            get {
                return ResourceManager.GetString("XenonLight", resourceCulture);
            }
        }
    }
}
