//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZKonfigurator.BusinessModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OptionsDisplayResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsDisplayResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFZKonfigurator.BusinessModels.Resources.OptionsDisplayResx", typeof(OptionsDisplayResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        internal static string Varnish_Beige {
            get {
                return ResourceManager.GetString("Varnish_Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwarz.
        /// </summary>
        internal static string Varnish_Black {
            get {
                return ResourceManager.GetString("Varnish_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blau.
        /// </summary>
        internal static string Varnish_Blue {
            get {
                return ResourceManager.GetString("Varnish_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braun.
        /// </summary>
        internal static string Varnish_Brown {
            get {
                return ResourceManager.GetString("Varnish_Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grün.
        /// </summary>
        internal static string Varnish_Green {
            get {
                return ResourceManager.GetString("Varnish_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic.
        /// </summary>
        internal static string Varnish_Metallic {
            get {
                return ResourceManager.GetString("Varnish_Metallic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rot.
        /// </summary>
        internal static string Varnish_Red {
            get {
                return ResourceManager.GetString("Varnish_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silber.
        /// </summary>
        internal static string Varnish_Silver {
            get {
                return ResourceManager.GetString("Varnish_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiß.
        /// </summary>
        internal static string Varnish_White {
            get {
                return ResourceManager.GetString("Varnish_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelb.
        /// </summary>
        internal static string Varnish_Yellow {
            get {
                return ResourceManager.GetString("Varnish_Yellow", resourceCulture);
            }
        }
    }
}
