//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZKonfigurator.BusinessModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RimsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RimsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFZKonfigurator.BusinessModels.Resources.RimsResx", typeof(RimsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5fach-Doppelspeichen 16&quot;.
        /// </summary>
        internal static string FiveDoubleSpokes16 {
            get {
                return ResourceManager.GetString("FiveDoubleSpokes16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5fach-Doppelspeichen 18&quot;.
        /// </summary>
        internal static string FiveDoubleSpokes18 {
            get {
                return ResourceManager.GetString("FiveDoubleSpokes18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-Speichen 16&quot;.
        /// </summary>
        internal static string FiveSpokes16 {
            get {
                return ResourceManager.GetString("FiveSpokes16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-Speichen 18&quot;.
        /// </summary>
        internal static string FiveSpokes18 {
            get {
                return ResourceManager.GetString("FiveSpokes18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4fach-Vielspeichen 16&quot;.
        /// </summary>
        internal static string FourMultiSpokes16 {
            get {
                return ResourceManager.GetString("FourMultiSpokes16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4fach-Vielspeichen 18&quot;.
        /// </summary>
        internal static string FourMultiSpokes18 {
            get {
                return ResourceManager.GetString("FourMultiSpokes18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Speichen 16&quot;.
        /// </summary>
        internal static string FourSpokes16 {
            get {
                return ResourceManager.GetString("FourSpokes16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Speichen 18&quot;.
        /// </summary>
        internal static string FourSpokes18 {
            get {
                return ResourceManager.GetString("FourSpokes18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-Speichen 16&quot;.
        /// </summary>
        internal static string TenSpokes16 {
            get {
                return ResourceManager.GetString("TenSpokes16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-Speichen 18&quot;.
        /// </summary>
        internal static string TenSpokes18 {
            get {
                return ResourceManager.GetString("TenSpokes18", resourceCulture);
            }
        }
    }
}
