//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZKonfigurator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KonfiguratorResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KonfiguratorResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFZKonfigurator.Resources.KonfiguratorResx", typeof(KonfiguratorResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellen.
        /// </summary>
        public static string Caption_OrderButton {
            get {
                return ResourceManager.GetString("Caption_OrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler - Konfiguration konnte nicht angepasst werden.
        /// </summary>
        public static string Error_UpdateFailed {
            get {
                return ResourceManager.GetString("Error_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Adresse.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorleistung.
        /// </summary>
        public static string Label_EnginePower {
            get {
                return ResourceManager.GetString("Label_EnginePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        public static string Label_Price {
            get {
                return ResourceManager.GetString("Label_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lackierung.
        /// </summary>
        public static string Label_Varnish {
            get {
                return ResourceManager.GetString("Label_Varnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email eingeben....
        /// </summary>
        public static string Placeholder_Email {
            get {
                return ResourceManager.GetString("Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorleistung....
        /// </summary>
        public static string Placeholder_EnginePower {
            get {
                return ResourceManager.GetString("Placeholder_EnginePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name der Konfiguration....
        /// </summary>
        public static string Placeholder_Name {
            get {
                return ResourceManager.GetString("Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie eine Lackierung....
        /// </summary>
        public static string Placeholder_Varnish {
            get {
                return ResourceManager.GetString("Placeholder_Varnish", resourceCulture);
            }
        }
    }
}
